name=PicoButtonAsync
version=1.0.0
author=Soumyajit Chatterjee
maintainer=Soumyajit Chatterjee
sentence=A high-performance, async-safe button library for RP2040/RP2350.
paragraph=Utilizes parallel bitwise debouncing and the Pico SDK async_context for non-blocking, multi-core safe input handling. Compatible with Wi-Fi and USB stacks.
category=Signal Input
url=https://github.com/jit89/PicoButton
architectures=rp2040,rp2350
includes=PicoButtonAsync.h
